# Generated by Django 4.1 on 2024-02-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiece_Articolo', models.CharField(blank=True, max_length=7, unique=True)),
                ('nome_articolo', models.CharField(blank=True, max_length=30)),
                ('descrizione', models.CharField(blank=True, max_length=250)),
                ('unita_di_misura', models.CharField(choices=[('kg', 'Kilogrammo'), ('Lt', 'Litro'), ('Nr', 'Numero')], max_length=2)),
            ],
            options={
                'verbose_name': 'Articoli',
                'db_table': 'Articoli',
            },
        ),
    ]
