# Generated by Django 4.1 on 2024-02-07 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articolo',
            options={'verbose_name': 'Articolo', 'verbose_name_plural': 'Articoli'},
        ),
        migrations.RenameField(
            model_name='articolo',
            old_name='codiece_Articolo',
            new_name='codiece_articolo',
        ),
    ]
