# Generated by Django 4.1 on 2024-02-07 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0004_alter_categoria_immagine_categortia'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='id_categoria',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Prodotti.categoria'),
            preserve_default=False,
        ),
    ]
