# Generated by Django 4.1 on 2024-02-07 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0005_articolo_id_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categoria'},
        ),
        migrations.AlterField(
            model_name='articolo',
            name='id_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Prodotti.categoria'),
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='Categoria',
        ),
    ]
