# Generated by Django 4.1 on 2024-02-07 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0007_categoria_sottocategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sottocategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sottocategoria', models.CharField(blank=True, max_length=30)),
                ('gruppo', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='sottocategoria',
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_sottocategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Prodotti.sottocategoria'),
        ),
    ]
