# Generated by Django 4.1 on 2024-02-07 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0009_alter_sottocategoria_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='id_sottocategoria',
        ),
        migrations.AddField(
            model_name='sottocategoria',
            name='id_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Prodotti.categoria'),
        ),
    ]
