# Generated by Django 4.1 on 2024-02-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0010_remove_categoria_id_sottocategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sottocategoria',
            name='gruppo',
            field=models.IntegerField(),
        ),
    ]
