# Generated by Django 4.2.10 on 2024-02-08 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0011_alter_sottocategoria_gruppo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='immagine_categortia',
            new_name='immagine_categoria',
        ),
    ]
